name: Update Strava Miles

on:
  schedule:
    # Runs at 8:10 AM ET and then every 4 hours (converted to UTC)
    - cron: "10 12,16,20,0,4,8 * * *"
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  update-miles:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      # Step 4: Run the Strava update script
      - name: Run update script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.178536 }}
          STRAVA_CLIENT_SECRET: ${{ secrets.6d5b002612cdf8bf130633f82a4928573859e9cf }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.3775fa385d446bb05b15278e920c570bfedea95a }}
        run: python update_strava.py
